-- Insert data tipoc_cambio
INSERT INTO TIPO_CAMBIO(DIVISA, CODIGO, COMPRA, VENTA) VALUES('Dólar estadounidense', 'USD', 4.061, 4.071 );
INSERT INTO TIPO_CAMBIO(DIVISA, CODIGO, COMPRA, VENTA) VALUES('Sol Peruano', 'SOL', 4.061, 4.071 );
INSERT INTO TIPO_CAMBIO(DIVISA, CODIGO, COMPRA, VENTA) VALUES('Euro', 'EUR', 4.577, 4.762 );
INSERT INTO TIPO_CAMBIO(DIVISA, CODIGO, COMPRA, VENTA) VALUES('Yen japonés', 'JPY', 0.031, 0.038 );
INSERT INTO TIPO_CAMBIO(DIVISA, CODIGO, COMPRA, VENTA) VALUES('Libra esterlina', 'GBP', 5.384, 5.530 );


-- Insert data usuario
INSERT INTO USUARIO (USERNAME, PASSWORD, ENABLE) VALUES('admin', '$2a$10$BT8IaLxNRk5aVUD3TKIw6OWNB8cKxw7AhhrnppSIcfS7t6qzqyQOS', TRUE);
INSERT INTO USUARIO (USERNAME, PASSWORD, ENABLE) VALUES('dlache', '$2a$10$BT8IaLxNRk5aVUD3TKIw6OWNB8cKxw7AhhrnppSIcfS7t6qzqyQOS', TRUE);

-- Insert data roles
INSERT INTO AUTHORITY (USUARIO_ID, TIPO) VALUES(1, 'ROLE_ADMIN');
INSERT INTO AUTHORITY (USUARIO_ID, TIPO) VALUES(1, 'ROLE_USER');
INSERT INTO AUTHORITY (USUARIO_ID, TIPO) VALUES(2, 'ROLE_USER');

-- Insert data consulta